[all]
vm ansible_host=192.168.1.110 ansible_user=server ansible_password=server ansible_become_method=sudo ansible_become_pass=server ansible_ssh_common_args='-o StrictHostKeyChecking=no'
;vm ansible_host=192.168.124.88 ansible_user=vboxuser ansible_password=changeme ansible_become_method=sudo ansible_become_pass=changeme ansible_ssh_common_args='-o StrictHostKeyChecking=no'

